### ISSUE TITLE
Cant run the software

### ISSUE THREAD

**Issue by AnonymousReviewer1** [pdtrang/MetaBIDx#2]
When following the README instructions I get : 
 `build_signature_one_phase.go:4:5: "./ppt_filter" is relative, but relative import paths are not supported in module mode`
I tried to change it in the source to absolute path, but I then get:
build_signature_one_phase.go:4:5: "/home/AR1/Documents/reviews/23PhaBox/MetaBIDx-master/src/build_index/ppt_filter" is not a package path; see 'go help packages'

Any clue?

**Comment by pdtrang** [comment]
Hi,

Thanks for contacting us. Are you running the software on MacOS? Currently we only support running on Linux. Sorry for missing that information in the instruction, I'll update the README for clarification. 

In order to avoid similar issue, we released Linux executables for `build_index` and `query` which can be downloaded and run directly.
